spring:
  application:
    name: eureka-server
server:
  port: 1101
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default: http://${eureka.instance.hostname}:${server.port}/eureka/
