server:
  port: 1103
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/kong-ge/spring-cloud-config-repo/
          default-label: master
          search-paths: config
  application:
    name: config-server
eureka:
  client:
    region: custom
    availability-zones:
      custom: default # custom对应region 多个使用逗号隔开 default,hello
    service-url:
      default: http://localhost:1101/eureka/ # default对应availability-zones default
